apiVersion: apps/v1
kind: Deployment
metadata:
  name: comosus-server-jenkins 
  labels:
    app: comosus-server
spec:
  selector:
    matchLabels:
        app: comosus-server
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: comosus-server
    spec:
      containers:
        - name: comosus-server
          image: 947036392937.dkr.ecr.us-east-1.amazonaws.com/comosus-server-img:latest
          ports:
            - containerPort: 3100
              protocol: TCP
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: comosus-server
spec:
  selector:
    app: comosus-server
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
  type: LoadBalancer