---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DATABASE_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbkBjbHVzdGVyMC5vcG1uZS5tb25nb2RiLm5ldC9hLWNvbW9zdXM/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comosus-server-jenkins 
  labels:
    app: comosus-server
spec:
  selector:
    matchLabels:
        app: comosus-server
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: comosus-server
    spec:
      containers:
        - name: comosus-server
          image: 947036392937.dkr.ecr.us-east-1.amazonaws.com/comosus-server-img:latest
          ports:
            - containerPort: 3100
              protocol: TCP
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATABASE_URL

---
apiVersion: v1
kind: Service
metadata:
  name: comosus-server
spec:
  selector:
    app: comosus-server
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
  type: LoadBalancer