org: acomosus
app: comosus-server
service: comosus-server

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-2
  apiGateway:
    shouldStartNameWithService: true

functions:
  app:
    handler: dist/main.handler
    environment: ${ssm:/aws/reference/secretsmanager/prod/comosus-server}
    timeout: 10
    events:
      - http:
          method: any
          path: /{any+}

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/schema.prisma'
    - 'prisma/schema.prisma'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

plugins:
  - serverless-offline
